AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Application Model - DBCC Application
Globals:
  Function:
    Environment:
      Variables:
        APP_NAME:
          Ref: AppName
        APP_VERSION:
          Ref: AppVersion
        DDB_TABLE:
          Fn::Sub: ${AppName}-${Environment}
        S3_BUCKET_NAME:
          Fn::ImportValue: dbcConverterBucket
        SQS_CONVERTER_QUEUE:
          Fn::ImportValue: dbcConverterQueue
        SQS_EMAIL_QUEUE:
          Fn::ImportValue: dbcEmailQueue
    Runtime: python3.7
    Timeout: 30
Outputs:
  ApplicationApi:
    Description: API Gateway endpoint URL for the application
    Value:
      Fn::Sub: https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/
  dbccDynamoDbStreamArn:
    Description: DynamoDB Stream ARN
    Export:
      Name: dbccDynamoDb-streamarn
    Value:
      Fn::GetAtt:
      - dbccDynamoDb
      - StreamArn
  dbccDynamoDbTable:
    Description: DynamoDB Table Name
    Export:
      Name: dbccDynamoDb
    Value:
      Ref: dbccDynamoDb
Parameters:
  AppName:
    Default: sam-dbcc-converter
    Description: Name of the application
    Type: String
  AppVersion:
    Default: v1
    Description: Version of the application
    Type: String
  Environment:
    Default: dev
    Description: Name of the environment to deploy to
    Type: String
Resources:
  AppConverterFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/3d0d7a35fc513e4882b0d54560c7b6d7
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        SqsEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::ImportValue: dbcConverterQueue-ARN
          Type: SQS
      Handler: app.main
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - Arn
        - Action:
          - s3:*
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  AppProcessorFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/447eae0e821a6c455ef79c99b7798a4a
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        SqsEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::ImportValue: dbcConverterS3Queue-ARN
          Type: SQS
      Handler: app.main
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - Arn
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  AppVersionFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/cbb47bc2beee7e4797866d2dcd0bdf23
      DeploymentPreference:
        Hooks:
          PostTraffic:
            Ref: AppVersionPostTrafficHookFunction
          PreTraffic:
            Ref: AppVersionPreTrafficHookFunction
        Type: AllAtOnce
      Events:
        Version:
          Properties:
            Method: get
            Path: /version
            RestApiId:
              Ref: ApplicationApi
          Type: Api
      Handler: app.get_version
    Type: AWS::Serverless::Function
  AppVersionPostTrafficHookFunction:
    Properties:
      CodeUri: s3://snowco-sam-eu-west-1/65f17a9906f56909746c88777372a753
      DeploymentPreference:
        Enabled: false
      FunctionName: CodeDeployHook_postTrafficHook
      Handler: test_handler.test_version_post_traffic
      Policies:
      - Statement:
        - Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Ref: AppVersionFunction.Version
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  AppVersionPreTrafficHookFunction:
    Properties:
      CodeUri: s3://snowco-sam-eu-west-1/cbb47bc2beee7e4797866d2dcd0bdf23
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CurrentFunctionVersion:
            Ref: AppVersionFunction.Version
      FunctionName: CodeDeployHook_preTrafficHook
      Handler: test_handler.test_version_pre_traffic
      Policies:
      - Statement:
        - Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Ref: AppVersionFunction.Version
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  ApplicationApi:
    Properties:
      Name: ApplicationApi
      StageName:
        Ref: Environment
    Type: AWS::Serverless::Api
  ReturnEmailFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/affc3692fc1e67b4c31df767a00c5ea0
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        SqsEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::ImportValue: dbcEmailQueue-ARN
          Type: SQS
      Handler: app.main
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - Arn
        - Action:
          - ses:*
          Effect: Allow
          Resource: '*'
        - Action:
          - s3:*
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  StreamProcessorFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/f1b73e7aa74362d78b767950a9f8b1e6
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        DdbEvent:
          Properties:
            BatchSize: 1
            Enabled: true
            StartingPosition: LATEST
            Stream:
              Fn::GetAtt:
              - dbccDynamoDb
              - StreamArn
          Type: DynamoDB
      Handler: app.main
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - Arn
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - StreamArn
        - Action:
          - s3:*
          Effect: Allow
          Resource: '*'
        - Action:
          - sqs:*
          Effect: Allow
          Resource:
            Fn::ImportValue: dbcConverterQueue-ARN
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  dbccDynamoDb:
    Properties:
      AttributeDefinitions:
      - AttributeName: messageId
        AttributeType: S
      KeySchema:
      - AttributeName: messageId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName:
        Fn::Sub: ${AppName}-${Environment}
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
