AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Application Model - Python Application
Globals:
  Function:
    Environment:
      Variables:
        APP_NAME:
          Ref: AppName
        APP_VERSION:
          Ref: AppVersion
        DDB_TABLE:
          Fn::Sub: ${AppName}-${Environment}
    Runtime: python3.7
    Timeout: 3
Outputs:
  ApplicationApi:
    Description: API Gateway endpoint URL for the application
    Value:
      Fn::Sub: https://${ApplicationApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/
  dbcConverterBucket:
    Description: S3 Bucketname for dbc converter
    Export:
      Name: dbcConverterBucket
    Value:
      Ref: dbcConverterBucket
  dbcConverterQueue:
    Description: SQS Queue for DBC Converter
    Export:
      Name: dbcConverterQueue
    Value:
      Ref: dbcConverterQueue
  dbcConverterQueueArn:
    Description: ARN of SQS Queue for DBC Converter
    Export:
      Name: dbcConverterQueue-ARN
    Value:
      Fn::GetAtt:
      - dbcConverterQueue
      - Arn
  dbccDynamoDbStreamArn:
    Description: DynamoDB Stream ARN
    Export:
      Name: dbccDynamoDb-streamarn
    Value:
      Fn::GetAtt:
      - dbccDynamoDb
      - StreamArn
  dbccDynamoDbTable:
    Description: DynamoDB Table Name
    Export:
      Name: dbccDynamoDb
    Value:
      Ref: dbccDynamoDb
Parameters:
  AppName:
    Default: sam-dbcc-converter
    Description: Name of the application
    Type: String
  AppVersion:
    Default: v1
    Description: Version of the application
    Type: String
  Environment:
    Default: dev
    Description: Name of the environment to deploy to
    Type: String
  ReceiptRuleName:
    Default: mail-to-s3
    Type: String
  ReceiptRuleSetName:
    Default: mail-to-s3
    Type: String
Resources:
  AppProcessorFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/b03ca77213e82660610f1c42c8026f88
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        SqsEvent:
          Properties:
            BatchSize: 1
            Queue:
              Fn::GetAtt:
              - dbcConverterQueue
              - Arn
          Type: SQS
      Handler: app.main
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - Arn
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  AppVersionFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/6aba80e225cb5530a5414928512a723b
      DeploymentPreference:
        Hooks:
          PostTraffic:
            Ref: AppVersionPostTrafficHookFunction
          PreTraffic:
            Ref: AppVersionPreTrafficHookFunction
        Type: AllAtOnce
      Events:
        Version:
          Properties:
            Method: get
            Path: /version
            RestApiId:
              Ref: ApplicationApi
          Type: Api
      Handler: app.get_version
    Type: AWS::Serverless::Function
  AppVersionPostTrafficHookFunction:
    Properties:
      CodeUri: s3://snowco-sam-eu-west-1/baed91222f7d37ea84a45cb7d0481f03
      DeploymentPreference:
        Enabled: false
      FunctionName: CodeDeployHook_postTrafficHook
      Handler: test_handler.test_version_post_traffic
      Policies:
      - Statement:
        - Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Ref: AppVersionFunction.Version
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  AppVersionPreTrafficHookFunction:
    Properties:
      CodeUri: s3://snowco-sam-eu-west-1/baed91222f7d37ea84a45cb7d0481f03
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          CurrentFunctionVersion:
            Ref: AppVersionFunction.Version
      FunctionName: CodeDeployHook_preTrafficHook
      Handler: test_handler.test_version_pre_traffic
      Policies:
      - Statement:
        - Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - Statement:
        - Action:
          - lambda:InvokeFunction
          Effect: Allow
          Resource:
            Ref: AppVersionFunction.Version
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  ApplicationApi:
    Properties:
      Name: ApplicationApi
      StageName:
        Ref: Environment
    Type: AWS::Serverless::Api
  ReceiptRuleSet:
    Properties:
      RuleSetName:
        Ref: ReceiptRuleSetName
    Type: AWS::SES::ReceiptRuleSet
  StreamProcessorFunction:
    Properties:
      AutoPublishAlias: live
      CodeUri: s3://snowco-sam-eu-west-1/d92a8fa9ce854a60898b6aea42fd7545
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        DdbEvent:
          Properties:
            BatchSize: 1
            Enabled: true
            StartingPosition: LATEST
            Stream:
              Fn::GetAtt:
              - dbccDynamoDb
              - StreamArn
          Type: DynamoDB
      Handler: app.main
      Policies:
      - Statement:
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - Arn
        - Action:
          - dynamodb:*
          Effect: Allow
          Resource:
            Fn::GetAtt:
            - dbccDynamoDb
            - StreamArn
        - Action:
          - s3:*
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
    Type: AWS::Serverless::Function
  dbcConverterBucket:
    Properties:
      AccessControl: Private
      BucketName:
        Fn::Sub: ${AppName}-${Environment}-${AWS::Region}
      NotificationConfiguration:
        QueueConfigurations:
        - Event: s3:ObjectCreated:*
          Filter:
            S3Key:
              Rules:
              - Name: prefix
                Value: in
          Queue:
            Fn::GetAtt:
            - dbcConverterQueue
            - Arn
    Type: AWS::S3::Bucket
  dbcConverterBucketPolicy:
    Properties:
      Bucket:
        Ref: dbcConverterBucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:PutObject
          Effect: Allow
          Principal:
            Service:
            - ses.amazonaws.com
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: dbcConverterBucket
              - /*
    Type: AWS::S3::BucketPolicy
  dbcConverterQueue:
    Properties:
      QueueName: dbcConverterQueue
    Type: AWS::SQS::Queue
  dbcConverterQueuePolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - sqs:*
          Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
          Resource:
          - Fn::GetAtt:
            - dbcConverterQueue
            - Arn
      Queues:
      - Ref: dbcConverterQueue
    Type: AWS::SQS::QueuePolicy
  dbccDynamoDb:
    Properties:
      AttributeDefinitions:
      - AttributeName: messageId
        AttributeType: S
      KeySchema:
      - AttributeName: messageId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName:
        Fn::Sub: ${AppName}-${Environment}
    Type: AWS::DynamoDB::Table
  mailToS3Rule:
    DependsOn: ReceiptRuleSet
    Properties:
      Rule:
        Actions:
        - S3Action:
            BucketName:
              Ref: dbcConverterBucket
            ObjectKeyPrefix: in
        Enabled: true
        Name:
          Ref: ReceiptRuleName
        ScanEnabled: true
      RuleSetName:
        Ref: ReceiptRuleSetName
    Type: AWS::SES::ReceiptRule
Transform: AWS::Serverless-2016-10-31
